## Lab 1: SCM inrichten

Het is een best-practice om AWX te gebruiken in combinatie met een ``SCM`` (Source Control Management). Enkele voorbeelden zijn:

* Git
* Subversion
* Azure Devops

Alle playbooks, roles etc. van Ansible worden in deze ``SCM`` gezet. AWX download dan automatisch de laatste versie van het project, voordat een playbook wordt gestart. Bijkomend voordeel van een SCM is dat alle wijzigingen inzichtelijk zijn (wie heeft wat, wanneer gewijzigd).

### Task 1.1: Azure Devops inrichten

In deze workshop gebruiken we Azure DevOps. De werking is beide hetzelfde. 

* Maak een account aan op ??? (URL van Klant). Mocht je al reeds een account hebben, dan kun je deze uiteraard gewoon gebruiken voor deze workshop. 
* Log in met je Azure AD account
* Klik rechtsboven op ``New Project`` 
* Geef het project een naam (bijvoorbeeld ``awx-workshop``)

TIP: We maken later een credential aan waarmee AWX verbinding kan maken met Azure DevOps.

### Task 1.2: Azure DevOps Deploy Token aanmaken

Na het aanmaken van het project, wordt dit project automatisch geopend (Open anders het project via ``Projects`` (menu bovenin), ``Your Projects``). In het project maken we een deploy token aan, die we later gebruiken om AWX toegang te geven tot de Git Repository.

* Klik ``Settings`` aan de linkerkant en kies ``Repository``.
* Klik ``Expand`` achter ``Deploy Tokens``
* Geef de token een naam (Bijvoorbeeld ``awx-workshop-token``)
* Vink onder ``Scopes`` ``read_repository`` aan.
* Klik ``Create deploy token``
* Noteer de gegevens van de nieuwe token:
** Deploy Token username
** Deploy Token Password
+
CAUTION: De Deploy Token Password is **eenmalig zichtbaar**. Noteer deze dus goed! Mocht je het wachtwoord later kwijt zijn, dan zul je de token opnieuw aan moeten maken (en krijgt deze dus een nieuw wachtwoord).

### Task 1.3: Repository URL

De repository URL hebben we later nodig voor de koppeling in AWX.

In je project:

* Klik ``Project`` aan de linkerkant en kies ``Details``
* Klik rechtsboven op Clone en noteer de link die staat onder ``Clone with HTTPS``.

### Task 1.4: Hello world playbook aanmaken

We maken alvast een "Hello world" playbook aan, waarmee we later de basis functionaliteit van AWX kunnen testen. 

In je project:

* Klik ``Project`` aan de linkerkant en kies ``Details``
* Klik ``New file``
* Vul de filename met ``hello-world.yml``
* Vul het code veld met:
+
[source,role=copypaste]
----
---
- name: Hello World Sample
  hosts: all
  tasks:
  - name: Hello Message
    debug:
      msg: "Hello World!"
----
+
TIP: Let goed op de uitlijning met spaties!
+
====

* Klik ``Commit changes`` om de wijzigingen op te slaan

