## Lab 1: SCM inrichten

Het is een best-practice om AWX te gebruiken in combinatie met een ``SCM`` (Source Control Management). Enkele voorbeelden zijn:

* Git
* Subversion
* Azure Devops

Alle playbooks, roles etc. van Ansible worden in deze ``SCM`` gezet. AWX download dan automatisch de laatste versie van het project, voordat een playbook wordt gestart. Bijkomend voordeel van een SCM is dat alle wijzigingen inzichtelijk zijn (wie heeft wat, wanneer gewijzigd).

### Task 1.1: Azure Devops inrichten

In deze workshop gebruiken we Azure DevOps. Zie de mail van Danny! Als het goed is heeft iedereen een eigen Lab aangemaakt. 

### Task 1.2: Azure DevOps Deploy Token aanmaken

Het Deploy Token is nodig om een koppeling te maken tussen AWX en je Azure DevOps Lab.

Onderstaande stappen komen uit: https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Windows

- Sign in to your organization (https://dev.azure.com/{yourorganization}).

- From your home page, open user settings  and select Personal access tokens.

- Select + New Token.
 
- Name your token, select the organization where you want to use the token, and then set your token to automatically expire after a set number of days.

- Select the scopes for this token to authorize for your specific tasks. (Kies hier Full Access)

- When you're done, copy the token and store it in a secure location. For your security, it doesn't display again.


CAUTION: De Deploy Token Password is **eenmalig zichtbaar**. Noteer deze dus goed! Mocht je het wachtwoord later kwijt zijn, dan zul je de token opnieuw aan moeten maken (en krijgt deze dus een nieuw wachtwoord).

### Task 1.3: Repository URL 

De repository URL hebben we later nodig voor de koppeling in AWX. Onderstaande is hoe het werk met github, en nog niet getest met Azure DevOps.

In je project:

* Klik ``Project`` aan de linkerkant en kies ``Details``
* Klik rechtsboven op Clone en noteer de link die staat onder ``Clone with HTTPS``.

### Task 1.4: Hello world playbook aanmaken

We maken alvast een "Hello world" playbook aan, waarmee we later de basis functionaliteit van AWX kunnen testen. 

In je project:

* Klik ``Project`` aan de linkerkant en kies ``Details``
* Klik ``New file``
* Vul de filename met ``hello-world.yml``
* Vul het code veld met:
+
[source,role=copypaste]
----
---
- name: Hello World Sample
  hosts: all
  tasks:
  - name: Hello Message
    debug:
      msg: "Hello World!"
----
+
TIP: Let goed op de uitlijning met spaties!
+
====

* Klik ``Commit changes`` om de wijzigingen op te slaan

