## Lab 8 AWX Roles

In AWX kun je, net als Ansible Engine, roles gebruiken om je playbooks te vereenvoudigen. Deze roles kunnen in de directory ``roles`` bij het playbook project gezet worden (in je ``SCM``, ofwel Azure DevOps in deze workshop). In de praktijk is het gebruikelijk dat roles in een apart project gezet worden. Het is zelfs mogelijk om AWX roles rechtstreeks van Ansible Galaxy te laten downloaden. In beide gevallen definieer je de role in de file ``roles/requirements.yml``. De blog op https://www.ansible.com/blog/using-ansible-and-ansible-tower-with-shared-roles legt uit hoe dat precies werkt.

### Task 8.1 Playbook met role toevoegen

* Log in op ``Azure Devops`` en voeg de volgende 2 files toe (Kijk eventueel terug in Lab 1), let op dat je de hostnames van je webservers invult bij address:
* ``loadbalancer-role.yml``:
+
[source,role=copypaste]
----
---
- hosts: "{{ target_host }}"

  vars:
    haproxy_backend_servers:
    - name: web1
      address: <webserver-hostname-01>:80
    - name: web2
      address: <webserver-hostname-02>:80

  roles:
  - { role: geerlingguy.haproxy }
----
+
* ``roles/requirements.yml``:
+
[source,role=copypaste]
----
- src: geerlingguy.haproxy
----
+
* Open ``Ansible Tower``
* Kies ``Projects``
* Ververs het project
+
TIP: Het verversen van het project is nodig om de playbooks zichtbaar te maken in het template.
+
* Voeg templates toe voor het nieuwe playbook ``loadbalancer-role.yml``
** Zet de inventory goed voor ``loadbalancer-role.yml``
+
CAUTION: Let er op dat je de ``machine`` credential toevoegt. Vergeet daarnaast niet om ``Enable privilege escalation`` aan te vinken.

### Task 8.2 Template uitvoeren

* Voer de template ``Loadbalancer-role`` uit. 
* Bekijk onder ``Jobs`` de ``SCM Update`` job. In deze job is te zien dat Ansible Tower de requirements.yml detecteert en de role van ``Ansible Galaxy`` download.

TIP: Mocht er onverhoopt iets mis zijn gegaan, dan is het probleem mogelijk in de ``SCM Update`` job terug te vinden.



